In [21]:
# Biblioteca
import pandas as pd
import numpy as np

Realizando a importação do dataset <https://pycourse.s3.amazonaws.com/bike-sharing.csv> para 
análise utilizando o pandas

In [20]:
df = pd.read_csv('https://pycourse.s3.amazonaws.com/bike-sharing.csv')

## Opção 1:  Para responder as questões do enunciado do desafio.

In [3]:
#tamanho do dataset
df.shape

(17379, 17)

In [4]:
# Media da coluna Windspeed
df['windspeed'].mean()

0.19009760630646177

In [5]:
# Media da coluna temp
df['temp'].mean()

0.4969871684216583

In [6]:
# Quantidade de registros para 2011
len(df.loc[df['year'] == 0])

8645

In [7]:
# Quantidade de registros para 2012
len(df.loc[df['year'] == 1])

8734

In [8]:
# Quantas locações foram registradas para 2011
df.loc[df['year'] == 0]['total_count'].sum()

1243103

In [9]:
# Quantas locações foram registradas para 2012
df.loc[df['year'] == 1]['total_count'].sum()

2049576

In [11]:
#Qual estação do ano possui a maior média de locações
df.groupby(by = ['season'])['total_count'].mean().sort_values(ascending = False).head(1)

season
3    236.016237
Name: total_count, dtype: float64

In [12]:
# Qual estação do ano possui a menor média de locações
df.groupby(by = ['season'])['total_count'].mean().sort_values(ascending = True).head(1)

season
1    111.114569
Name: total_count, dtype: float64

In [13]:
# Qual horario do dia possui a maior media de locacao
df.groupby(by = ['hour'])['total_count'].mean().sort_values(ascending = False).head(1)

hour
17    461.452055
Name: total_count, dtype: float64

In [14]:
# Qual horario do dia possui a menor media de locacao
df.groupby(by = ['hour'])['total_count'].mean().sort_values(ascending = True).head(1)

hour
4    6.352941
Name: total_count, dtype: float64

In [15]:
# Qual dia da semana possui a maior média de locações
df.groupby(by = ['weekday'])['total_count'].mean().sort_values(ascending = False).head(1)

weekday
4    196.436665
Name: total_count, dtype: float64

In [16]:
# Qual dia da semana possui a menor média de locações
df.groupby(by = ['weekday'])['total_count'].mean().sort_values(ascending = True).head(1)

weekday
0    177.468825
Name: total_count, dtype: float64

In [17]:
# As quartas feiras, qual é o horario do dia tem a maior media de locação
df.loc[df['weekday'] == 3].groupby(by = ['hour'])['total_count'].mean().sort_values(ascending = False).head(1)

hour
17    513.144231
Name: total_count, dtype: float64

In [23]:
# Aos sabados feiras, qual é o horario do dia tem a maior media de locação
df.loc[df['weekday'] == 6].groupby(by = ['hour'])['total_count'].mean().sort_values(ascending = False).head(1)

hour
13    385.371429
Name: total_count, dtype: float64

### Opção 2 para responder as questões do enunciado

In [38]:
df.describe()

---------------------

,rec_id,season,year,month,hour,is_holiday,weekday,is_workingday,weather_condition,temp,atemp,humidity,windspeed,casual,registered,total_count
count,17379.0000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
mean,8690.0000,2.501640,0.502561,6.537775,11.546752,0.028770,3.003683,0.682721,1.425283,0.496987,0.475775,0.627229,0.190098,35.676218,153.786869,189.463088
std,5017.0295,1.106918,0.500008,3.438776,6.914405,0.167165,2.005771,0.465431,0.639357,0.192556,0.171850,0.192930,0.122340,49.305030,151.357286,181.387599
min,1.0000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,4345.5000,2.000000,0.000000,4.000000,6.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,4.000000,34.000000,40.000000
50%,8690.0000,3.000000,1.000000,7.000000,12.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,17.000000,115.000000,142.000000
75%,13034.5000,3.000000,1.000000,10.000000,18.000000,0.000000,5.000000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,48.000000,220.000000,281.000000
max,17379.0000,4.000000,1.000000,12.000000,23.000000,1.000000,6.000000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,367.000000,886.000000,977.000000

In [32]:
#Para melhor visualização dos dados: 

df

,datetime,rec_id,season,year,month,hour,is_holiday,weekday,is_workingday,weather_condition,temp,atemp,humidity,windspeed,casual,registered,total_count
0,2011-01-01,1,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,2,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,3,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,4,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,5,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,2012-12-31,17375,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,2012-12-31,17376,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,2012-12-31,17377,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,2012-12-31,17378,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,2012-12-31,17379,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [36]:
print(df[['datetime', 'season']])

         datetime  season
0      2011-01-01       1
1      2011-01-01       1
2      2011-01-01       1
3      2011-01-01       1
4      2011-01-01       1
...           ...     ...
17374  2012-12-31       1
17375  2012-12-31       1
17376  2012-12-31       1
17377  2012-12-31       1
17378  2012-12-31       1

[17379 rows x 2 columns]